# Generated by Django 5.1.2 on 2024-10-27 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'managed': False},
        ),
    ]
