# Generated by Django 5.1.2 on 2024-10-27 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_expense_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'managed': True},
        ),
    ]
