# Generated by Django 5.1.2 on 2024-11-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_rename_name_expense_category_expense_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={},
        ),
        migrations.RemoveField(
            model_name='expense',
            name='description',
        ),
        migrations.AddField(
            model_name='expense',
            name='name',
            field=models.CharField(default='Default Name', max_length=100),
            preserve_default=False,
        ),
    ]
