# Generated by Django 5.1.2 on 2024-12-02 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_income'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Income',
        ),
    ]
