# Generated by Django 5.1.2 on 2024-12-04 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_delete_income'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='category',
            new_name='source',
        ),
    ]
