# Generated by Django 5.1.2 on 2024-10-24 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0002_alter_income_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='source',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='income',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
