# Generated by Django 5.1.2 on 2024-11-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0003_income_source_alter_income_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='income',
            name='source',
            field=models.CharField(max_length=100),
        ),
    ]
