# Generated by Django 5.1.2 on 2024-12-03 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_expense_income'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='category',
            new_name='source',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='budget',
        ),
    ]
